### ISSUE TITLE
Healing temp HP doesn't appear to be working properly

### ISSUE THREAD

**Issue by Orionox** [jessev14/health-monitor#2]
When I add temp HP via a spell no notification pops up in chat. Also, when I add temp Hp to the character sheet directly it shows up as normal healing even though I have the option to show temp HP as something else.

**Comment by jessev14** [comment]
there's no setting to make temp HP changes look different than normal HP changes. changes to MAX temp HP or MAX normal HP are tracked and colored differently if you have that module setting enabled.

I'm not able to reproduce your spell issue. could you describe how you are applying the healing?

**Comment by Orionox** [comment]
![Capture](https://user-images.githubusercontent.com/20059838/158046411-ba1b979e-99ae-4646-b18a-53a540148e90.PNG)
Here's how the spell is set up. When doing normal "healing" the spell does get a health notification, but when doing healing(Temporary) no healing notification

**Comment by jessev14** [comment]
How are you actually applying the healing though? right clicking the roll in chat? or midi or something?

**Comment by Orionox** [comment]
I'm using midi and clicking the roll button.

**Comment by jessev14** [comment]
I'm not able to reproduce. Both Healing and Healing (Temporary) cause the message to appear and add the corresponding type of health to the target.
