### ISSUE TITLE
Health Monitor not working with Foundry V10

### ISSUE THREAD

**Issue by kiloforce** [jessev14/health-monitor#3]
The Health Monitor Icon is not appearing on the toolbar, and the chat logs are not reporting changes to HP.  When looking at the Javascript console, getting a Javascript error:

![image](https://user-images.githubusercontent.com/433058/189519887-5faa42e4-2d36-4c40-af5e-345ce4272e15.png)

Foundry V10.285.  Only module loaded for testing purposes.  Health Monitor Module v2.1.3.

**Comment by jessev14** [comment]
Fixed in version 2.2.0.

**Comment by kiloforce** [comment]
This Java Script error is gone, and the Player's health monitor is functional, thank you.

But, it appears that the Monster/NPC health monitor is not reporting in V10.  Created a new issue, as the above does not match the issue now:

https://github.com/jessev14/health-monitor/issues/4
