### ISSUE TITLE
Monster and NPC Health Monitor Not Working in V10

### ISSUE THREAD

**Issue by kiloforce** [jessev14/health-monitor#4]
The "Player Character" health monitor appears to be working, but the "Non-Player Character" (NPCs and Monsters) does not appear to be functional anymore.

![image](https://user-images.githubusercontent.com/433058/189556074-46422090-e623-4c72-a3e5-e5aba03ff206.png)

Foundry V10.285.  Health Monitor Module v2.2.0.

Using default settings, except for "Show Health Monitor Toggle":
![image](https://user-images.githubusercontent.com/433058/189557443-43d98f58-472c-4cd1-95d6-e07e4d768658.png)

**Comment by jessev14** [comment]
Fixed in version 2.2.1.

**Comment by kiloforce** [comment]
Working, thanks!
