### ISSUE TITLE
Error when updating Temp HP from macro

### ISSUE THREAD

**Issue by nschoenwald** [jessev14/health-monitor#6]
I am using the following macro to update my players' temp HP for the inspiring leader feat:
`for(const user of game.users) await user.character?.applyTempHP(7);
`
This results in an error and no messages are generated by healthEstimate:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/72390280/211191735-67ecec17-77da-4d6f-8d89-12fdcf0e524e.png">

**Comment by jessev14** [comment]
Fixed in 2.2.5.
