### ISSUE TITLE
Temp HP are shown as green message with "heals for X damage" text

### ISSUE THREAD

**Issue by nschoenwald** [jessev14/health-monitor#7]
I am using this macro to set my players' characters temp HP:

`for(const user of game.users) user.character?.applyTempHP(7);`

As of 2.2.5 this does display a Health Monitor message, but the color and text are like the regular HP increased ("Player heals for 7 damage"). I would expect and prefer this to be a blue message with Temp HP specific text.

**Comment by jessev14** [comment]
The blue messages are for increases to max HP / max temp HP.
