### ISSUE TITLE
[Feature Request] Add separate text and color for gaining temp hp

### ISSUE THREAD

**Issue by nschoenwald** [jessev14/health-monitor#8]
Currently, when a character gains temp hp, the message is the same as when regular hp are healed.
It would be great if adding temp hp resulted in a message clarifying this, ideally with a separate color.

**Comment by jessev14** [comment]
This module was funded by a commission. I unfortunately don't have the means to develop on my own time. I'm happy to accept a pull request if you'd like to implement it yourself. Or you can reach out to me on Discord to discuss funding the feature `enso#0361`.

**Comment by jessev14** [comment]
Added in version 3.0.0.
